version: "3.8"

services:

  postgres:
    container_name: postgres_coll
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ykks
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 5s
      retries: 5


