# Generated by Django 5.0.2 on 2024-03-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedictionary',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
