# Generated by Django 5.0.2 on 2024-02-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/%Y/%m/%d/', verbose_name='photo'),
        ),
    ]
