# Generated by Django 5.0.2 on 2024-02-26 09:34

import games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameslinks',
            name='name',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='game',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=games.models.game_poster_path),
        ),
    ]
