# Generated by Django 5.0.2 on 2024-02-22 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_game_status_game_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameStudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='game',
            name='studio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='games.gamestudio'),
        ),
    ]
